function Hd = Filter_BP_IIR(Fs,Fstop1,Fpass1,Fpass2,Fstop2)
%FILTER_BP_IIR 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 25-Jan-2024 10:14:55

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 1e+11;  % Sampling Frequency
% 
% Fstop1 = 9800000000;   % First Stopband Frequency
% Fpass1 = 9900000000;   % First Passband Frequency
% Fpass2 = 10100000000;  % Second Passband Frequency
% Fstop2 = 10200000000;  % Second Stopband Frequency
Astop1 = 60;           % First Stopband Attenuation (dB)
Apass  = 1;            % Passband Ripple (dB)
Astop2 = 80;           % Second Stopband Attenuation (dB)
match  = 'passband';   % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
